# Generated by Django 5.0.7 on 2024-08-07 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Chemical Categories',
                'db_table': 'chemical_categories',
            },
        ),
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chemicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('composition', models.CharField(choices=[('solid', 'Solid'), ('liquid', 'Liquid'), ('gas', 'Gas')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('chemical_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.chemicalcategory')),
            ],
            options={
                'verbose_name_plural': 'Chemicals',
                'db_table': 'chemicals',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=100)),
                ('equipment_model', models.CharField(max_length=100)),
                ('equipment_model_number', models.CharField(max_length=100)),
                ('equipment_purchase_date', models.DateField()),
                ('equipment_model_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipment_model_quantity', models.IntegerField()),
                ('equipment_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.equipmentcategory')),
            ],
        ),
    ]
