# Generated by Django 5.0.7 on 2024-10-22 16:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicals',
            name='date_acquired',
            field=models.DateField(default=django.utils.timezone.now, help_text='Enter date acquired of the chemical.'),
            preserve_default=False,
        ),
    ]
