# Generated by Django 5.0.7 on 2024-08-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_chemicals_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemicals',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
