# Generated by Django 5.0.7 on 2024-08-07 09:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_chemicals_expiration_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name_plural': 'Equipment'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chemicalcategory',
            name='category_name',
            field=models.CharField(help_text='Enter the chemical category name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='chemicals',
            name='chemical_category',
            field=models.ForeignKey(help_text='Select the chemical category.', on_delete=django.db.models.deletion.CASCADE, to='inventory.chemicalcategory'),
        ),
        migrations.AlterField(
            model_name='chemicals',
            name='composition',
            field=models.CharField(choices=[('solid', 'Solid'), ('liquid', 'Liquid'), ('gas', 'Gas')], help_text='Select the chemical composition.', max_length=10),
        ),
        migrations.AlterField(
            model_name='chemicals',
            name='expiration_date',
            field=models.DateField(help_text='Enter the expiration date of the chemical.'),
        ),
        migrations.AlterField(
            model_name='chemicals',
            name='name',
            field=models.CharField(help_text='Enter the chemical name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='chemicals',
            name='quantity',
            field=models.IntegerField(help_text='Enter the quantity of the chemical.'),
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='equipment',
        ),
    ]
