# Generated by Django 5.0.7 on 2024-08-07 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_equipment_options_equipment_date_added_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentcategory',
            options={'verbose_name_plural': 'Equipment Categories'},
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_category',
            field=models.ForeignKey(help_text='Select the equipment category.', on_delete=django.db.models.deletion.CASCADE, to='inventory.equipmentcategory'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_model',
            field=models.CharField(help_text='Enter the equipment model.', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_model_cost',
            field=models.DecimalField(decimal_places=2, help_text='Enter the equipment model cost.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_model_number',
            field=models.CharField(help_text='Enter the equipment model number.', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_model_quantity',
            field=models.IntegerField(help_text='Enter the equipment model quantity.'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_name',
            field=models.CharField(help_text='Enter the equipment name.', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_purchase_date',
            field=models.DateField(help_text='Enter the equipment purchase date.'),
        ),
    ]
