# Generated by Django 5.0.7 on 2024-08-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_equipmentcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicals',
            name='chemical_units',
            field=models.CharField(blank=True, choices=[('g', 'Gram'), ('mg', 'Milligram'), ('μg', 'Microgram'), ('kg', 'Kilogram'), ('L', 'Liter'), ('mL', 'Milliliter'), ('μL', 'Microliter'), ('mol', 'Mole'), ('mmol', 'Millimole'), ('μmol', 'Micromole'), ('M', 'Molarity'), ('m', 'Molality'), ('X', 'Mole fraction'), ('ppm', 'Parts per million'), ('ppb', 'Parts per billion'), ('J', 'Joule'), ('kJ', 'Kilojoule'), ('eV', 'Electronvolt'), ('°C', 'Degrees Celsius'), ('°F', 'Degrees Fahrenheit'), ('K', 'Kelvin'), ('Pa', 'Pascal'), ('kPa', 'Kilopascal'), ('atm', 'Atmosphere'), ('mmHg', 'Millimeters of mercury')], help_text='Select the chemical units.', max_length=10, null=True),
        ),
    ]
