# Generated by Django 5.0.7 on 2024-08-08 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_chemicals_chemical_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemicals',
            name='availability',
            field=models.BooleanField(default=True, help_text='Select if the chemical is available.'),
        ),
        migrations.AddField(
            model_name='chemicals',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
